### ISSUE TITLE
0.4.0 Roadmap

### ISSUE THREAD

**Issue by benmerckx** [alineacms/alinea#317]
Base
- [x] Show status for publishing
- [x] Finish mutation -> changesets (save, publish, archive, remove, order, move, upload)
- [x] Provide temporary thumbnail for files that are not done uploading
- [x] Update cloud to accept new changeset type
- [x] Write tests for common actions like renaming path to make sure they produce the wanted changeset
- [x] Configure Yjs provider
- [ ] Re-think `createCms` vs `createNextCms`
- [x] Apply draft cookies to preview route url fetching logic

Theme
- [x] Add a phase switcher in the EntryHeader
- [x] Add an options dropdown for actions other than the main action in EntryHeader
- [x] Re-add theme dark/light switcher in bottom left side of the sidebar
- [x] Check responsive css

Bugs
- [x] Media explorer: Unable to link entries that are located in another root
- [x] Media explorer: should not be able to select Media Library as file/image
- [x] Fetching image and file data

Backlog
- [x] Seeding: children & locales
- [x] Nested Rich text fields
- [x] Cleaner UI for inserting blocks in Rich text fields
- [x] Re-write docs

External
- [ ] https://github.com/vercel/next.js/pull/55006

**Comment by benmerckx** [comment]
Release. Unfortunately Next.js has not accepted our PR yet but I've added a section in the docs
