### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by benmerckx** [alineacms/alinea#370]
Missing features
- [x] Self-hosting: instead of the modular approach we had I think we can go with a single well-tested setup where we require both a Github token and some persistence (database or redis)
- [ ] Moving entries (#13)

Confusing APIs: we have a final call to break these before we're tied to supporting them for the long term
- [x] Re-think `createCms` vs `createNextCms`. Evaluate what we need to support other frameworks and see if we really need the distinction here. Once option is changing the import based on framework (from 'alinea/next', 'alinea/remix').
- [x] #373
- [x] Boolean arguments are sometimes prefixed with is (Type: isHidden, isContainer) and sometimes without: (Field: hidden, readOnly)
- [ ] The query engine is quite complete in functionality but now it needs to become intuitive as well. I think only selecting from linked Entries is todo here.
- [x] There's still potential for name-clashes in the List and Link field which will combine your fields and the internal things such as id, index and type. Can we restructure data to avoid this completely? (#29)
- [x] Clean up the exports from the alinea package. It would be nice to be able to import * as alinea from 'alinea' because it will help with tree shaking. I think we could still support the current default export as well.

Documentation
- [x] Document usage in Next.js edge routes
- [ ] Examples/starters, featured on the website
- [ ] Bring back demo

Test scaling
- [ ] Are we ready for 10k, 100k entries?

External
- [ ] Seems Next.js is not bothered to support smaller packages for now, but one can hope: https://github.com/vercel/next.js/pull/55006
- [x] Making sure custom fields and views are excluded form website bundle requires: https://github.com/vercel/next.js/issues/50285
- [x] Previews are flaky in production: https://github.com/vercel/next.js/issues/61377
- [x] Don't use rado/driver to support < tsc 5.6

Nice-to-have
- [x] (Next) merge backend and preview into a single handler
- [ ] Finish and document how to seed pages.
- [ ] Integrate images and columns deeply into the Rich text field. I think there's a great opportunity to make those "primitive" content blocks that can be rendered just as easily as the other content types (heading, paragraph, ...).
- [x] Focus point selection for images.
- [ ] Adding extra fields to the MediaFile type.
- [ ] Design?
- [ ] Validate locales with Intl.Locale
- [ ] Translate the dashboard UI
- [ ] The Link vs entry, file, image, url field api is not super intuitive. It'd be nicer to wrap them so we can also target the configuration of each link picker much better:
````
alinea.link(  
  alinea.image('Pick an image'),  
  alinea.file('Or a file')  
)  
````
